class KarutaCard(object):
	def __init__(self, name, number, syllables):
		self.name = name #Space separated: "A ki no", "Fu"
		self.number = number #number of the card: Akino = 1, Fu = 22
		self.syllable_count = syllables #Number of syllables. Akino = 3, Fu = 1

	def __str__(self):
		return "Card: {}".format(self.name)

cards = [
	KarutaCard("a ki no", 1, 3),
	KarutaCard("ha ru su", 2, 3),
	KarutaCard("a shi", 3, 2),
	KarutaCard("ta go", 4, 2),
	KarutaCard("o ku", 5, 2),
	KarutaCard("ka sa", 6, 2),
	KarutaCard("a ma no", 7, 3),
	KarutaCard("wa ga i", 8, 3),
	KarutaCard("ha na no", 9, 3),
	KarutaCard("ko re", 10, 2),
	KarutaCard("wa ta no ha ra ya", 11, 6),
	KarutaCard("a ma tsu", 12, 3),
	KarutaCard("tsu ku", 13, 2),
	KarutaCard("mi chi", 14, 2),
	KarutaCard("ki mi ga ta me ha", 15, 6),
	KarutaCard("ta chi", 16, 2),
	KarutaCard("chi ha", 17, 2),
	KarutaCard("su", 18, 1),
	KarutaCard("na ni wa ga", 19, 4),
	KarutaCard("wa bi", 20, 2),
	KarutaCard("i ma ko", 21, 3),
	KarutaCard("fu", 22, 1),
	KarutaCard("tsu ki", 23, 2),
	KarutaCard("ko no", 24, 2),
	KarutaCard("na ni shi", 25, 3),
	KarutaCard("o gu", 26, 2),
	KarutaCard("mi ka no", 27, 3),
	KarutaCard("ya ma za", 28, 3),
	KarutaCard("ko ko ro a", 29, 4),
	KarutaCard("a ri a", 30, 3),
	KarutaCard("a sa bo ra ke a", 31, 6),
	KarutaCard("ya ma ga", 32, 3),
	KarutaCard("hi sa", 33, 2),
	KarutaCard("ta re", 34, 2),
	KarutaCard("hi to ha", 35, 3),
	KarutaCard("na tsu", 36, 2),
	KarutaCard("shi ra", 37, 2),
	KarutaCard("wa su ra", 38, 3),
	KarutaCard("a sa ji", 39, 3),
	KarutaCard("shi no", 40, 2),
	KarutaCard("ko i", 41, 2),
	KarutaCard("chi gi ri ki", 42, 4),
	KarutaCard("a i", 43, 2),
	KarutaCard("o o ko", 44, 3),
	KarutaCard("a wa re", 45, 3),
	KarutaCard("yu ra", 46, 2),
	KarutaCard("ya e", 47, 2),
	KarutaCard("ka ze o", 48, 3),
	KarutaCard("mi ka ki", 49, 3),
	KarutaCard("ki mi ga ta me o", 50, 6),
	KarutaCard("ka ku", 51, 2),
	KarutaCard("a ke", 52, 2),
	KarutaCard("na ge ki", 53, 3),
	KarutaCard("wa su re", 54, 3),
	KarutaCard("ta ki", 55, 2),
	KarutaCard("a ra za", 56, 3),
	KarutaCard("me", 57, 1),
	KarutaCard("a ri ma", 58, 3),
	KarutaCard("ya su ra", 59, 3),
	KarutaCard("o o e", 60, 3),
	KarutaCard("i ni ", 61, 2),
	KarutaCard("yo o", 62, 2),
	KarutaCard("i ma wa", 63, 3),
	KarutaCard("a sa bo ra ke u", 64, 6),
	KarutaCard("u ra", 65, 2),
	KarutaCard("mo ro", 66, 2),
	KarutaCard("ha ru no", 67, 3),
	KarutaCard("ko ko ro ni", 68, 4),
	KarutaCard("a ra shi", 69, 3),
	KarutaCard("sa", 70, 1),
	KarutaCard("yu u", 71, 2),
	KarutaCard("o to", 72, 2),
	KarutaCard("ta ka", 73, 2),
	KarutaCard("u ka", 74, 2),
	KarutaCard("chi gi ri o", 75, 4),
	KarutaCard("wa ta na ha ra ko", 76, 6),
	KarutaCard("se", 77, 1),
	KarutaCard("a wa ji", 78, 3),
	KarutaCard("a ki ka", 79, 3),
	KarutaCard("na ga ka", 80, 3),
	KarutaCard("ho", 81, 1),
	KarutaCard("o mo", 82, 2),
	KarutaCard("yo no na ka yo", 83, 5),
	KarutaCard("na ga ra", 84, 3),
	KarutaCard("yo mo", 85, 2),
	KarutaCard("na ge ke", 86, 3),
	KarutaCard("mu", 87, 1),
	KarutaCard("na ni wa e", 88, 4),
	KarutaCard("ta ma", 89, 2),
	KarutaCard("mi se", 90, 2),
	KarutaCard("ki ri", 91, 2),
	KarutaCard("wa ga so", 92, 3),
	KarutaCard("yo no na ka wa", 93, 5),
	KarutaCard("mi yo", 94, 2),
	KarutaCard("o o ke", 95, 3),
	KarutaCard("ha na sa", 96, 3),
	KarutaCard("ko nu", 97, 2),
	KarutaCard("ka ze so", 98, 3),
	KarutaCard("hi to mo", 99, 3),
	KarutaCard("mo mo", 100, 2),


]
